#!/bin/bash

# Define the directory containing the wallpapers
WALLPAPER_DIR="~/Pictures/"

# Make sure we can connect to the desktop environment
export DISPLAY=":0"
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u)/bus"

cd ~/Pictures
wget https://mythologyworldwide.com/wp-content/uploads/2024/09/mythologyworldwide.com-Bigfoot-A-Myth-or-a-Reality-The-Scientific-Evidence.webp

# Determine the current color scheme to decide which property to set
COLOR_SCHEME=$(gsettings get org.gnome.desktop.interface color-scheme)

# Change the wallpaper based on the color scheme
if [ "$COLOR_SCHEME" = "'prefer-dark'" ]; then
    # Set the wallpaper for dark theme
    gsettings set org.gnome.desktop.background picture-uri-dark ~/Pictures/mythologyworldwide.com-Bigfoot-A-Myth-or-a-Reality-The-Scientific-Evidence.webp
else
    # Set the wallpaper for light theme
    gsettings set org.gnome.desktop.background picture-uri ~/Pictures/mythologyworldwide.com-Bigfoot-A-Myth-or-a-Reality-The-Scientific-Evidence.webp
fi
