#!/bin/bash

# Define the directory containing the wallpapers
WALLPAPER_DIR="~/Pictures/"

# Make sure we can connect to the desktop environment
export DISPLAY=":0"
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u)/bus"

cd ~/Pictures
wget https://cdn.pixabay.com/photo/2022/09/27/19/46/ai-generated-7483596_960_720.jpg

# Determine the current color scheme to decide which property to set
COLOR_SCHEME=$(gsettings get org.gnome.desktop.interface color-scheme)

# Change the wallpaper based on the color scheme
if [ "$COLOR_SCHEME" = "'prefer-dark'" ]; then
    # Set the wallpaper for dark theme
    gsettings set org.gnome.desktop.background picture-uri-dark ai-generated-7483596_960_720.jpg
else
    # Set the wallpaper for light theme
    gsettings set org.gnome.desktop.background picture-uri ai-generated-7483596_960_720.jpg
fi
